### ISSUE TITLE
Clean up MVVM architecture

### ISSUE THREAD

**Issue by RavioliRanger** [RavioliRanger/voskle-live-transcribe#1]
### Goals:

- Decouple components that should not touch
- Clean up/Expand communication via viewModel

### TODO:

- [x] Move VoskHub form MainActivity into the Application State
- [x] Clean up viewModel

### Extra features:

- [x] Recording pauses now automatically in onPause()

Branch is tested and ready to merge
